recipient = [0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab]
server_hash = [0x5d, 0xde, 0xed, 0x97, 0xa3, 0x95, 0x09, 0x19, 0xf4, 0x9a, 0xb7, 0xe4, 0x13, 0xee, 0xb1, 0x27, 0x24, 0x67, 0xa1, 0x29, 0xb6, 0xa7, 0x5b, 0x59, 0xac, 0x81, 0xda, 0x05, 0x16, 0xbd, 0xfb, 0x92]
id_commitment = [0xa1, 0xc7, 0x6f, 0x30, 0x4f, 0xba, 0x04, 0x9c, 0xa3, 0xc1, 0xed, 0xd8, 0x5d, 0x7a, 0xef, 0xa1, 0xf3, 0xe8, 0x00, 0x17, 0x61, 0x53, 0x08, 0x4a, 0x58, 0xe1, 0x49, 0x4e, 0x08, 0x86, 0x38, 0xf5]
status_commitment = [0x72, 0x15, 0xde, 0xae, 0x27, 0x5b, 0xac, 0x9a, 0x08, 0xb1, 0xc4, 0x8a, 0x13, 0xeb, 0xf9, 0xc2, 0x43, 0x30, 0x73, 0x2d, 0xe0, 0x2f, 0x94, 0x70, 0x9f, 0xef, 0xcd, 0x8b, 0x0a, 0x9b, 0x75, 0xd8]
nuip = "123456789012345"
salt = [0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11]
server_domain = "civil-registry-mock.onrender.com        "
status = "No Vigente (Fallecido)"
status_blinder = [0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22]
