recipient = [0x03, 0xf7, 0x2d, 0x58, 0x59, 0x85, 0x8a, 0xff, 0x7b, 0x93, 0x09, 0x6b, 0x4a, 0xd9, 0x59, 0x34, 0x42, 0xdd, 0x23, 0x27]
server_hash = [0x5d, 0xde, 0xed, 0x97, 0xa3, 0x95, 0x09, 0x19, 0xf4, 0x9a, 0xb7, 0xe4, 0x13, 0xee, 0xb1, 0x27, 0x24, 0x67, 0xa1, 0x29, 0xb6, 0xa7, 0x5b, 0x59, 0xac, 0x81, 0xda, 0x05, 0x16, 0xbd, 0xfb, 0x92]
id_commitment = [0xbc, 0x3a, 0xa7, 0x55, 0xf7, 0xa5, 0x76, 0x60, 0x32, 0x26, 0x12, 0xe3, 0x8b, 0x80, 0x7a, 0xbf, 0xb6, 0xd4, 0xda, 0xfa, 0x11, 0xb0, 0x1d, 0x44, 0x8f, 0xc6, 0xc0, 0x36, 0x9d, 0xeb, 0xa1, 0x3e]
status_commitment = [0x72, 0x15, 0xde, 0xae, 0x27, 0x5b, 0xac, 0x9a, 0x08, 0xb1, 0xc4, 0x8a, 0x13, 0xeb, 0xf9, 0xc2, 0x43, 0x30, 0x73, 0x2d, 0xe0, 0x2f, 0x94, 0x70, 0x9f, 0xef, 0xcd, 0x8b, 0x0a, 0x9b, 0x75, 0xd8]
nuip = "123            "
salt = [0x5b, 0x63, 0x5e, 0x98, 0xe5, 0x87, 0x5d, 0xa7, 0xa0, 0xf4, 0x82, 0xb9, 0xfb, 0x3a, 0xf8, 0xf0, 0xe9, 0xe3, 0xb0, 0x70, 0x99, 0x7f, 0x90, 0x4f, 0x40, 0x20, 0xd7, 0x83, 0xca, 0x82, 0xe5, 0x03]
server_domain = "civil-registry-mock.onrender.com        "
status = "No Vigente (Fallecido)"
status_blinder = [0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22]
